server:
  port : 8090

# For H2
#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true

# For MYSQL
spring:
  datasource:
    url: jdbc:mysql://sql7.freemysqlhosting.net:3306/sql7743737?serverTimezone=UTC
    username: sql7743737
    password: nZbpAk5Dmw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true

externalApi:
  polls:
    url: https://polls-system.onrender.com/polls
#   For localhost
#   url: http://localhost:8080/polls